/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yuli_myapplication_JNI_NativeHelper */

#ifndef _Included_com_example_yuli_myapplication_JNI_NativeHelper
#define _Included_com_example_yuli_myapplication_JNI_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yuli_myapplication_JNI_NativeHelper
 * Method:    getAppKey
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_example_yuli_myapplication_JNI_NativeHelper_getAppKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
