/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yuli_myapplication_JNI_MyJNI */

#ifndef _Included_com_example_yuli_myapplication_JNI_MyJNI
#define _Included_com_example_yuli_myapplication_JNI_MyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yuli_myapplication_JNI_MyJNI
 * Method:    getAppkey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_yuli_myapplication_JNI_MyJNI_getAppkey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
